DFE-Digital/register-training-providers

app/views/landing_page/start.html.erb, app/views/layouts/application.html.erb, spec/features/landing_page_spec.rb, spec/rails_helper.rb, spec/support/features/matchers/heading_matcher.rb, spec/support/features/matchers/phase_banner_matcher.rb, spec/support/features/navigation_helpers.rb
Does it look right?
https://trello.com/c/EuQV9nM8/73-implement-the-start-page
=> [0073] Added specs for start page

app/controllers/heartbeat_controller.rb, config/routes.rb, spec/requests/heartbeat_spec.rb
Added `/healthcheck`endpoint
Added `/sha`endpoint
Added `/ping`endpoint
=> [0071] Added heartbeat endpoints

.github/workflows/build-and-deploy.yml, Gemfile, terraform/application/config/review.tfvars.json
Updating the review env vars in tfvars
make review terraform-plan PR_NUMBER=13
Ensure the terraform shows correct app name for review
=> Remving env var in review tfvar

.erdconfig, Gemfile, Gemfile.lock, lib/tasks/auto_generate_diagram.rake
Added rails-erd gem and related settings
=> [0076] Added rails-erd gem

.gitignore, Gemfile, config/database.yml
Amended the git ignore to reflect https://github.com/bkeepers/dotenv?tab=readme-ov-file#customizing-rails
Re order and fold in groups for the gemfile
Removed excessive database config
=> [0076] Fix minor issues

.github/workflows/build-and-deploy.yml, terraform/application/config/review.yml
Updating the review rails env
Adding back the github job condition for deploy_review
Pull this branch 2330-new-service-register-of-training-providers
make review terraform-apply PR_NUMBER=13
Ensure the app is at https://register-training-providers-pr-13.test.teacherservices.cloud/
=> Adding rails env

.github/workflows/build-and-deploy.yml, Makefile, terraform/application/config/production.yml, terraform/application/config/qa.yml, terraform/application/config/staging.yml, terraform/application/output.tf, terraform/application/variables.tf, terraform/domains/environment_domains/.terraform.lock.hcl, terraform/domains/environment_domains/config/qa.tfvars.json, terraform/domains/environment_domains/config/staging.tfvars.json, terraform/domains/environment_domains/output.tf, terraform/domains/infrastructure/.terraform.lock.hcl
Adding domain configs
Updating makefile for domains
Adding rails env
Configuring the healthcheck
Commenting out smoke-test job
Pull this branch 2330-new-service-register-of-training-providers and run
make qa domains-plan
make staging domains-plan
make production domains-plan CONFIRM_PRODUCTION=yes
Ensure terraform shows no errors
Review the external urls output
Validate the resources to be created, are as needed
review GitHub job runs
verify the deployed review app
=> Adding domain config, updating rails env

.github/workflows/ci.yml, Dockerfile, Gemfile, Gemfile.lock, config/application.rb, config/environments/production.rb, config/environments/qa.rb, config/environments/review.rb, config/environments/staging.rb
=> [xxxx] Environment additional setups

.github/workflows/build-and-deploy.yml
Adding deploy qa and domain infra CICD
domain infra deployed using terraform
qa is deployed through the terraform
=> Adding deploy qa and domain infra CICD

Makefile
Fixing the domain infra CICD
domain infra plan run
https://github.com/DFE-Digital/register-training-providers/actions/runs/15049329833/job/42299882111
=> Fixing domain infra plan

.github/workflows/build-and-deploy.yml
Configured the slackwebhook and added to the workflow
Tested
https://ukgovernmentdfe.slack.com/archives/C08LHQ5UJHX/p1747401426159649
=> Adding slack webhook

.github/workflows/build-and-deploy.yml
Adding build job write permission to packages and PR
Review workflow
=> Adding build job write permission to packages and PR

.github/workflows/build-and-deploy.yml
Adding CICD for staging env
Staging env app deployed
https://register-training-providers-staging.test.teacherservices.cloud/
=> Adding CICD for staging env

.env.example, .env.review, .rubocop.yml, app/controllers/heartbeat_controller.rb, app/controllers/sign_in_controller.rb, app/views/landing_page/start.html.erb, app/views/layouts/application.html.erb, app/views/sign_in/index.html.erb, config/application.rb, config/locales/en.yml, config/routes.rb, lib/env.rb, lib/rubocop/cop/environment/no_direct_env_access.rb, spec/features/auth/sign_in_page_spec.rb, spec/features/landing_page_spec.rb, spec/lib/env_spec.rb, spec/requests/heartbeat_spec.rb, spec/rubocop/cop/environment/no_direct_env_access_spec.rb, spec/support/env_helper.rb
Added env wrapper and related 
Added sign in page that changes based on env used, review apps are defaulted to persona, otherwise it uses DfE Sign-In
https://register-training-providers-pr-46.test.teacherservices.cloud/sign-in
=> [0076] Initial Sign in step

app/assets/stylesheets/application.sass.scss
=> [0077] Fixed missing fonts and images

.github/pull_request_template.md
PR needs some info to make it more informative
Bare minimal optional pull request template
Is this useful?
=> [0110]  Add optional pull request template

app/models/user.rb, spec/models/user_spec.rb
User ordering based on first then last name
Added user ordering based on first then last name
To be used in later PRs
=> [0078] Added user ordering based on first then last name

app/components/check_your_answers/view.html.erb, app/components/check_your_answers/view.rb, app/helpers/application_helper.rb, app/views/layouts/application.html.erb, app/views/users/new.html.erb, spec/components/check_your_answers/view_preview.rb, spec/components/check_your_answers/view_spec.rb, spec/helpers/application_helper_spec.rb, spec/views/users/new.html.erb_spec.rb
Check your answer as a view component
Added check your answers view components
Amended the page data to take in account of caption
https://register-training-providers-pr-89.test.teacherservices.cloud/view_components/check_your_answers/view/new_user_check_your_answers
=> [0079] Added check your answers view components

app/components/pagination_display/view.html.erb
Pagination readability
Fixed pagination readability, by making it bold
https://register-training-providers-pr-120.test.teacherservices.cloud/view_components/pagination_display/
=> [0084] Fixed pagination readability

adr/00003-smoke-tests-strategy.md
ADR
Justification for not having smoke tests
Read the ADR
=> [0085] Added ADR for smoke test

.env.staging
Staging env for DfE Sign-In
Added staging env for DfE Sign-In
You can login via DfE Sign-in
=> [0124] Added staging env for DfE Sign-In

.github/workflows/build-and-deploy.yml
:shipit: 
:shipit: 
related to
=> [0085] Fix merge method

.tool-versions, Gemfile.lock
Fixed the build
Amended postgres to use the latest
Solargraph-rails down version
This is the result of  `bundle update`
=> [xxxx] Broken build

.env.example, .env.production, .tool-versions, config/initializers/omniauth/dfe_sign_in.rb
Prod env for DfE Sign-In
Added prod env for DfE Sign-In
You can login via DfE Sign-in
=> [0124] Added prod env

app/controllers/providers_controller.rb, spec/features/end_to_end/providers/providers_listing_spec.rb
Providers per page
Amended to be 10 providers per page
=> [0175] Amended provider to be 10 per page

app/controllers/providers/accreditations/check_controller.rb, app/controllers/providers/accreditations_controller.rb, app/forms/providers/accreditation.rb, app/helpers/summary_helper.rb, app/models/accreditation.rb, app/models/temporary_record.rb, app/policies/accreditation_policy.rb, app/views/layouts/application.html.erb, app/views/providers/accreditations/check/show.html.erb, app/views/providers/accreditations/edit.html.erb, config/locales/en.yml, config/routes.rb, spec/features/end_to_end/accreditations/viewing_provider_accreditations_spec.rb, spec/forms/providers/accreditation_spec.rb, spec/helpers/summary_helper_spec.rb
=> [193] accreditation update

.env.example, .env.production, .env.qa, .env.review, .env.staging, README.md, adr/00005-using-ordnance-survey-api.md
ordnance survey api
Write up
Makes sense?
=> [0206] Write up for using ordnance survey api

app/views/errors/internal_server_error.html.erb, app/views/errors/not_found.html.erb, app/views/errors/unprocessable_entity.html.erb
Trailing closing tags
Removed trailing closing tags
Bad lint autocorrect
=> [xxxx] Removed bad linting autocorrect
