DFE-Digital/register-training-providers

.github/workflows/delete-review-app.yml

Adding permission for delete review workflow
Check workflow to see if the run is successful
https://github.com/DFE-Digital/register-training-providers/actions/runs/14998100664

Adding permission for delete review workflow

---

app/assets/stylesheets/application.sass.scss

When running
```bash
bundle exec rails assets:precompile
```
```txt
Deprecation Warning [import]: Sass @import rules are deprecated and will be removed in Dart Sass 3.0.0.
More info and automated migrator: https://sass-lang.com/d/import
...
Warning: Importing using 'govuk/all' is deprecated. Update your import statement to import 'govuk/index'. To silence this warning, update $govuk-suppressed-warnings with key: "import-using-all"
...
```

[0099] Fixed sass issues

---

app/helpers/support_email_helper.rb
app/views/sign_in/new.html.erb
config/locales/en.yml
config/routes.rb

Viewable at
https://register-training-providers-pr-54.test.teacherservices.cloud/sign-in/user-not-found
Based on 
https://becoming-a-teacher.design-history.education.gov.uk/register-of-training-providers/service-error-pages/#account-not-recognised

[0077] Added user not found page

---

.github/workflows/build-and-deploy.yml
terraform/application/application.tf
terraform/application/config/production.tfvars.json
terraform/application/database.tf
terraform/application/variables.tf

Adding CICD for prod env, production readyness
prod app is deployed https://register-training-providers-production.teacherservices.cloud/
Validate
make production terraform-plan CONFIRM_PRODUCTION=yes

Adding CICD to prod env, configuring for production readyness

---

.github/workflows/backup-db.yml
terraform/application/config/staging.tfvars.json

Fixing the DB backup workflow and adding storage account for db backup in staging env
Check the db backup taken for staging env
https://github.com/DFE-Digital/register-training-providers/actions/runs/15343051809/job/43173213782

Fixing the DB backup workflow and adding storage account for db backup in staging env

---

app/controllers/application_controller.rb
app/controllers/landing_page_controller.rb
app/controllers/personas_controller.rb
app/controllers/sessions_controller.rb
app/controllers/sign_in_controller.rb
app/lib/service_pattern.rb
app/services/dfe_sign_in_users/update.rb
app/views/personas/index.html.erb
config/routes.rb

Sign in as a persona/test user
Added the sign in flow for persona
Viewable here
https://register-training-providers-pr-49.test.teacherservices.cloud/
Use the browser back button as the sign out is not in place yet.
The full signin flow in with 
- a valid user
- a soft deleted user
- a non existence user
All of which is to mimic what shape a user can attempt to long in.
For the valid user there is not much to see other then empty `Providers`
For the other 2 users they will land on the `Ask for an account to access the Register of training providers`

[0077] Implement personas

---

.github/workflows/backup-db.yml
terraform/application/application.tf

Enabling the scheduled prod db backup, adding probe path
Manual DB Backup
https://github.com/DFE-Digital/register-training-providers/actions/runs/15343051809
Scheduled DB Backup
TBD

Enabling the scheduled prod db backup, adding probe path

---

app/controllers/application_controller.rb
app/controllers/users_controller.rb
app/views/layouts/application.html.erb
app/views/users/index.html.erb
app/views/users/new.html.erb
config/initializers/govuk_formbuilder.rb
config/routes.rb
spec/support/features/matchers/back_link_matcher.rb
spec/support/features/matchers/capybara_node_helper.rb
spec/support/features/matchers/error_summary_matcher.rb
spec/support/features/matchers/pagination_matcher.rb
spec/views/users/index.html.erb_spec.rb
spec/views/users/new.html.erb_spec.rb

Add support user flow
Added functionality to add user 
Journey begins here
https://register-training-providers-pr-77.test.teacherservices.cloud/users
- Click on `Add user` button
- Fill in `Personal details` form with invalid data
- Click on continue
- Review validations
- Correct invalid data
- Click on continue
- Review flash message
Check your answers page
With `Add user` button

[0079] Add support user flow

---

config/initializers/semantic_logger.rb

Semantic logger
Amended initialiser for semantic logger to be more relaxed.
Previously it was only enabled on development and production.
:ship: 
Bypassing test as it generates a lot of noise

[0116] Amended initialiser for semantic logger to be more relaxed

---

.env.example
.env.test
.solargraph.yml
app/controllers/landing_page_controller.rb
app/controllers/sign_out_controller.rb
app/views/layouts/application.html.erb
config/initializers/omniauth/dfe_sign_in.rb
config/routes.rb
spec/features/end_to_end/sign_in_and_out_flow_spec.rb
spec/features/end_to_end/users/user_management_spec.rb
spec/features/landing_page_spec.rb
spec/rails_helper.rb
spec/support/features.rb
spec/support/features/authentication_helper.rb
spec/support/features/dfe_sign_in_user_helper.rb
spec/support/features/navigation_helper.rb
spec/support/omniauth.rb

DfE Sign-in and the related user sign in/out process
Added the reminder of the dfe sign in expected configuration
Added the sign out link/process
Amended landing page to redirect if authenticated
- The features specs
- The sign out link
The sign in and sign out completion was needed as they based on actual `dfe` onimauth strategy
- in it absences it was making feature specs a no go
-  as  `persona`/`developer`/`test user` onimauth strategy has no real value to be embed in testing
Out of scope
-  actually working of DfE Sign-in, as it currently being onboarded. 
When actual configuration is available it should just work.

[0072] DfESsign-in setup

---

.erdconfig
Dockerfile
Procfile.dev
app/jobs/demo_job.rb
bin/jobs
config/application.rb
config/environments/production.rb
config/queue.yml
config/recurring.yml
db/migrate/20250617085424_add_solid_queue.rb
db/schema.rb
spec/jobs/demo_job_spec.rb
spec/support/job.rb
terraform/application/application.tf
terraform/application/variables.tf

Solid queue
Add solid queue
Add worker
https://github.com/rails/solid_queue/?tab=readme-ov-file#single-database-configuration
1. You need the worker
```bash
bin/rails solid_queue:start
```
2. You need to drop in
```bash
bin/rails rails console
```
3. You need to enqueue
```ruby
DemoJob.set(wait: 10.seconds).perform_later("foo")
```
4. Then check on `finished_at`
```ruby
SolidQueue::Job.last
```
For local, you can substitute 1 & 2 with  
```bash
bin/dev
```
For review app, you can skip 1 and just ssh onto the box
This commit to be dropped before merge
https://github.com/DFE-Digital/register-training-providers/pull/96/commits/462453fc3e878dff7e470339a167c91495558ab5

[0079] Add solid queue

---

.rubocop.yml
app/controllers/check_controller.rb
app/controllers/users/check_controller.rb
app/controllers/users_controller.rb
app/views/users/check/new.html.erb
config/locales/en.yml
config/routes.rb
spec/components/check_your_answers/view_preview.rb
spec/features/end_to_end/users/creating_user_spec.rb
spec/helpers/application_helper_spec.rb
spec/support/features/matchers/notification_banner_matcher.rb

The add a support user flow, with check your answers.
The check your answers, will replay the previously saved captured from the previous form.
Landing on the user listing page, via nature traversing or via `cancel`/`back` will have any previous temporary record of that user cleared.
There is a daily scheduled task to clear expired temporary record.
Caption/page title is aligned with [design history}(https://becoming-a-teacher.design-history.education.gov.uk/register-of-training-providers/how-we-use-heading-captions/#include-captions-in-the-page-title)
The temporary record is cleared on the user listing page, regardless, this enable no tracking of where user have transverse.
This is mainly a workflow for `Check your answers` there is a number of cross with other items that we will be …

[0079] Add support user flow with check answer page

---

app/components/user_summary/view.rb
app/controllers/users_controller.rb
app/views/users/index.html.erb
app/views/users/show.html.erb
config/routes.rb
spec/components/user_summary/view_spec.rb
spec/views/users/index.html.erb_spec.rb
test/factories/users.rb

The view support user page
Added the view support user page
This is where the page starts to have two call to action
- delete user
- edit user
Both covered elsewhere
Does the page look right?

[0080] Added view support user page

---

.erb_lint.yml
app/components/check_your_answers/view.html.erb
app/components/check_your_answers/view.rb
app/controllers/check_controller.rb
app/controllers/users_controller.rb
app/models/user.rb
app/views/layouts/application.html.erb
app/views/users/_fields.html.erb
app/views/users/check/show.html.erb
app/views/users/edit.html.erb
app/views/users/index.html.erb
config/locales/en.yml
config/routes.rb
spec/components/check_your_answers/view_preview.rb
spec/components/check_your_answers/view_spec.rb
spec/features/end_to_end/users/creating_user_spec.rb
spec/features/end_to_end/users/editing_user_spec.rb
spec/models/user_spec.rb
spec/support/features/matchers/heading_matcher.rb
spec/support/features/matchers/notification_banner_matcher.rb

The change support user details flow
Added the change support user details flow
1. Create a new user
2. Navigate to the newly created user
3. Click on `Change` links
4. Change some thing
5. Check your answers
6. Save user

[0082] Added the change support user details flow

---

app/controllers/check_controller.rb
app/controllers/users/check_controller.rb
app/views/users/edit.html.erb
app/views/users/new.html.erb
spec/features/end_to_end/users/editing_user_spec.rb
spec/views/users/edit.html.erb_spec.rb

Snag for change user details
Fixed change link, it was defaulted to new user instead of edit user
Fixed back link, it needed to know where go in a dead loop
Amended to `d` from `D`, casing matters
https://trello.com/c/oiJ0xdhO/#comment-6863c3502a207845c4651b9c
https://trello.com/c/oiJ0xdhO/#comment-6863c25968e64ced53a99dc5
https://trello.com/c/oiJ0xdhO/#comment-6863c3b93af29aca0286a1ef

[0082] Fix snag for change user details

---

app/controllers/providers_controller.rb
app/forms/providers/provider_type.rb
app/models/concerns/enums/accreditation_status_enum.rb
app/models/concerns/enums/provider_type_enum.rb
app/models/concerns/validators/provider_type_validator.rb
app/models/provider.rb
app/views/providers/new_type.html.erb
config/locales/en.yml
config/routes.rb
spec/features/end_to_end/providers/creating_provider_spec.rb
spec/forms/providers/provider_type_spec.rb
spec/models/concerns/enums/accreditation_status_enum_spec.rb
spec/models/concerns/enums/provider_type_enum_spec.rb
spec/models/concerns/validators/provider_type_validator._spec.rb
spec/models/provider_spec.rb
spec/views/provider/new_type.html.erb_spec.rb
test/factories/providers.rb

There is a total of 3 pages before the `Check your answers`? page
This is the second page `Provider type`
The others are `Is the accredited provider?` and `Provider details`
The back links on `Provider type` page navigates and repopulates the value on `Is the accredited provider?` page
`spec/features/end_to_end/providers/creating_provider_spec.rb` has denoted a few places that stills needs to be implemented
This is the full journey
```mermaid
flowchart TD
classDef page fill:#E0F7FA,stroke:#00ACC1,stroke-width:2px,color:#01579B,font-weight:bold;
classDef button fill:#FFF8E1,stroke:#F57C00,stroke-width:2px,color:#E65100,font-style:italic;
classDef action fill:#E8F5E9,stroke:#2E7D32,stroke-width:2px,color:#1B5E20,font-weight:bold;
%% Subgraph styling
style Step1 …
```

[0135] Add provider partial flow `Provider type` page

---

Gemfile
Gemfile.lock
lib/data/seed-providers.csv
lib/tasks/example_data.rake
lib/tasks/import_providers.rake

CSV import
Added a rake task to import the csv for providers
Designed so it imports for Review apps and QA, idempont, it will only add new or update existing
https://register-training-providers-pr-150.test.teacherservices.cloud/
```bash
bundle exec rake example_data:generate
bundle exec rake import:providers CSV=some/path/to.csv
```
There is still some validation issue on the raw data hence only a subset is imported and no `scitt`, or `accredited` provider
```
639/851 providers was imported.
```

[0132] View provider list with csv import

---

.editorconfig
app/controllers/providers_controller.rb
app/helpers/summary_helper.rb
app/views/providers/show.html.erb
spec/features/end_to_end/providers/view_provider_spec.rb
spec/helpers/summary_helper_spec.rb
spec/views/provider/show.html.erb_spec.rb
test/factories/providers.rb

View provider
Added ability to view a provider
On the listing of provider the operating name/title is now clickable

[0136] View provider

---

Dockerfile
terraform/application/application.tf

Configure RoTP app to run as non root
Configure RoTP app to run as non root
Check the review app
https://trello.com/c/HTFH3K0a/2412-security-aks-containers-run-as-non-root-user-rtp

Configure RoTP app to run as non root

---

app/controllers/errors_controller.rb
app/views/errors/internal_server_error.html.erb
app/views/errors/not_found.html.erb
app/views/errors/unprocessable_entity.html.erb
config/routes.rb
spec/requests/errors_spec.rb

Service error pages
Amended `not_found`
Amended `unprocessable_entity`
Amended `internal_server_error`
`not_found` will show if the user is signed in or not
Design history for [Page not found](https://becoming-a-teacher.design-history.education.gov.uk/register-of-training-providers/service-error-pages/#page-not-found)
signed in or not and then visit
https://register-training-providers-pr-169.test.teacherservices.cloud/404/
> notice the navigation components
`internal_server_error` and `unprocessable_entity` are the same, (it will not show if the user is signed in or not)
https://register-training-providers-pr-169.test.teacherservices.cloud/422
https://register-training-providers-pr-169.test.teacherservices.cloud/500
Design history for [The service is …

[0177] Service error pages

---

terraform/application/database.tf
terraform/application/variables.tf

Add variable for PostgreSQL version so its possible to upgrade the postgres  server per environment
Add variable for PostgreSQL version
make env terraform-plan
Plan shows no changes as the default postgres version is set to 16
https://trello.com/c/u1ZbJf5h/2450-rotp-change-postgresql-version-to-a-variable

Add variable for PostgreSQL version

---

app/assets/stylesheets/application.sass.scss
app/helpers/footer_helper.rb
app/views/layouts/application.html.erb
spec/helpers/footer_helper_spec.rb

Footer
Amended footer to be more standardised
Previously there was a lot of customization

[0183] Amended footer to be more standardised

---

app/helpers/summary_helper.rb
spec/views/provider/index.html.erb_spec.rb

The archived tag
Added archived tag for the provider on the provider list page
Given a provider 
when it is archived 
then the archived tag is shown on the provider list page

[0231] Added archived tag

---

app/models/provider.rb
spec/features/end_to_end/providers/change_provider_details_spec.rb
spec/views/provider/details/new.html.erb_spec.rb
spec/views/provider/edit.html.erb_spec.rb

Ordering of error messages
Fixed the ordering of errors
Is it ordered correctly?

[0236] Fixed ordering of error messages
